title: Xilong Liu  # your name (or website title) here
logo: "/images/IMG_0457.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <a href="https://www.linkedin.com/in/xilong-liu-337289221/">LinkedIn</a> 
  <br>
  <a href="https://github.com/lxl0816/Xilong-Liu-/blob/master/pdf/Xilong%20Liu_Resume_Final_1.11.23.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/lxl0816">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
